#!/bin/bash

# APP=${1} if not provided, go in bash
NAME="exportface2s3"

if [ "${1}" == "" ]; then 
  APP="`echo ${0} | sed 's/[\.\/]//g'`"
  RUN="/bin/bash"
else
  APP=${1}
  RUN="python /app.py"
fi

docker build -t ${NAME} .

docker run -it --rm ${NAME} python -c "import cv2; print(cv2.__version__)"

sudo xhost local:root
docker run -it --rm \
  -v `pwd`/${APP}:/src/app.py \
  -v `pwd`/faces:/src/faces \
  -v `pwd`/haarcascade_frontalface_default.xml:/src/haarcascade_frontalface_default.xml \
  -v `pwd`:/src \
  --device=/dev/vcsm \
  --device=/dev/vchiq \
  --device /dev/video0 \
  -e DISPLAY=$DISPLAY \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  --hostname `hostname` \
  ${NAME} ${RUN}

